services:
  db:
    image: postgres:16
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    restart: unless-stopped
    volumes:
      - LinkLeafDb:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  LinkLeafDb: